### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by magx2** [craigburke/js-closure-wrap-asset-pipeline#1]
Will you update your dependencies? I mean `com.bertramlabs.plugins:asset-pipeline-core`.

**Comment by craigburke** [comment]
@magx2 the `asset-pipeline-core` dependency isn't included in the final jar for this so you specify whatever version of `asset-pipeline-core` you want to use in your project. Is there a particular version of `asset-pipeline-core` that doesn't seem to work with this?

**Comment by craigburke** [comment]
Feel free to reopen if it's not working with a particular version of asset pipeline but I'm closing this one for now.
