### ISSUE TITLE
Adding support for coffee script 

### ISSUE THREAD

**Issue by magx2** [craigburke/js-closure-wrap-asset-pipeline#2]
Can you add support for coffee script? As far as I know the only thing that you need to add is one ```if```in ```JsClosureWrapProcessor``` that checks if file extension is js or coffee.

**Comment by craigburke** [comment]
@magx2 I actually don't think you need to use this module since the coffee script compiler wraps each file in a function by default. Is that not what you're seeing?

**Comment by magx2** [comment]
Thanks. I will try this!

śr., 23.11.2016, 17:59 użytkownik Craig Burke notifications@github.com
napisał:

**Comment by craigburke** [comment]
I'm pretty sure about that, but feel free to re-open this issue if I'm wrong.
